require:
  - rubocop-rspec
  - rubocop-performance


AllCops:
  NewCops: enable

  TargetRubyVersion: 3.2

  Exclude:
    - 'spec/*'
    - 'vendor/**/*'
    
  DisplayCopNames: true

Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'spec/*'

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'spec/*'

Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'spec/*'
    - '*.gemspec'

Layout/EndOfLine:
  EnforcedStyle: lf

Style/Documentation:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true