AllCops:
  TargetRubyVersion: 3.2

  Exclude:
    - 'spec/*'

Layout/EndOfLine:
  EnforcedStyle: lf

  
Metrics/BlockLength:
  Max: 25

Metrics/MethodLength:
  Max: 25


Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always